FROM restreamio/gstreamer:latest-prod

ENTRYPOINT sleep 2 && gst-launch-1.0 videotestsrc pattern=ball ! video/x-raw,format=RGB, framerate=15/1, width=640, height=480 !  jpegenc ! multipartmux boundary=spionisto ! tcpclientsink host=dummy_mjepg_stream port=9999